### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by alex-bender** [ant4g0nist/rudroid#1]
It's a nice post! Thanks a lot for that. Your dms are closed, so I'm writing here. What's your plan for a future development?

**Comment by ant4g0nist** [comment]
Hi Alex. Glad you liked the post. My DM is now open :)

About the future development, currently I do not have any plans as such. If people need/like it, then can come up with some roadmap and work on rewriting and improving :)

**Comment by SeeFlowerX** [comment]
Will it have more features similar to unidbg ? I think rust version will be faster~
 
- https://github.com/zhkl0228/unidbg

**Comment by ant4g0nist** [comment]
Hey @SeeFlowerX. This is just an educational emulator I made for the blog. Sorry but I do not have any plans on adding more features to this at this point. I'll be really glad if anyone wants to improve this though. :)
